const assert = require("node:assert/strict");
const fs = require("node:fs");

const html = fs.readFileSync("index.html", "utf8");
const sql = fs.readFileSync("supabase.sql", "utf8");
const loginFunction = fs.readFileSync("supabase/functions/pin-login/index.ts", "utf8");
const serviceWorker = fs.readFileSync("service-worker.js", "utf8");
const manifest = fs.readFileSync("manifest.webmanifest", "utf8");
const car = fs.readFileSync("car.md", "utf8");
const scriptStart = html.lastIndexOf("<script>") + 8;
const scriptEnd = html.indexOf("</script>", scriptStart);

assert.doesNotThrow(() => new Function(html.slice(scriptStart, scriptEnd)));
assert.equal((html.match(/aria-label="PIN digit/g) || []).length, 4);
assert.doesNotMatch(html, /5514|signInAnonymously|ensureAnonymousSession|pin\s*!==/);
assert.match(html, /functions\.invoke\("pin-login"/);
assert.match(html, /auth\.verifyOtp/);
assert.match(html, /id="keep-signed-in"/);
assert.match(html, /persistSession:\s*true/);
assert.match(html, /storage:\s*authStorage/);
assert.match(html, /sessionStorage\.getItem/);
assert.match(html, /\.on\("postgres_changes"/);
assert.match(html, /indexedDB\.open\("super-important-tasks", 1\)/);
assert.match(html, /queueMutation/);
assert.match(html, /flushQueuedMutations/);
assert.match(html, /addEventListener\("online"/);
assert.match(html, /if \(!navigator\.onLine\)/);
assert.doesNotMatch(html, /setInterval\s*\(/);
assert.match(html, /id="progress-circle"/);
assert.match(html, /id="progress-ring"/);
assert.match(html, /id="progress-label">0 \/ 0 done/);
assert.match(html, /function renderProgress\(tasks\)/);
assert.match(html, /document\.body\.classList\.remove\("session-loading"\)/);
assert.doesNotMatch(html, /Still to do|Add a super important task|Hold a ring segment|>Synced</);
assert.match(html, /pointerdown", reveal/);
assert.match(html, /text-decoration-thickness: 2px/);
assert.match(html, /function visibleTasks\(tasks, requestedDate\)/);
assert.match(html, /Not completed on/);
assert.match(html, /id="completed-task-list"/);
assert.match(html, /onAuthStateChange/);
assert.doesNotThrow(() => JSON.parse(fs.readFileSync("manifest.webmanifest")));
assert.doesNotThrow(() => JSON.parse(fs.readFileSync(".mcp.json")));
assert.match(sql, /verify_super_tasks_pin/);
assert.match(sql, /pin_hash = extensions\.crypt/);
assert.match(sql, /grant execute on function public\.verify_super_tasks_pin\(text, text\) to service_role/);
assert.match(sql, /super_important_tasks_private\.is_owner/);
assert.match(sql, /alter publication supabase_realtime add table/);
assert.match(sql, /super_important_tasks_daily_progress/);
assert.match(sql, /security_invoker = true/);
assert.match(sql, /function super_important_tasks_private\.fill_task_owner\(\)/);
assert.match(sql, /create trigger super_important_tasks_fill_owner/);
assert.match(sql, /if new\.user_id is null/);
assert.match(loginFunction, /admin\.rpc\("verify_super_tasks_pin"/);
assert.match(loginFunction, /admin\.auth\.admin\.generateLink/);
assert.doesNotMatch(loginFunction, /5514/);
assert.match(serviceWorker, /super-important-tasks-shell-v10/);
assert.match(serviceWorker, /SUPABASE_SDK_URL/);
assert.match(html, /\.\/logo\.png/);
assert.doesNotMatch(html + manifest + serviceWorker, /favicon\.ico|icons\/icon-(192|512)\.png/);
assert.match(manifest, /"src": "\.\/logo\.png"/);
assert.match(car, /isbvdvexguygczzgrdpl/);
assert.match(car, /Do not supply `user_id`/);

console.log("App checks passed");
